# Generated by Django 5.2.3 on 2025-08-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
    ]
